### ISSUE TITLE
Дополнить функциональность

### ISSUE THREAD

**Issue by krivtsov** [alexd73/accessibility_drupal_theme#1]
Спасибо за реализацию. Дополнить функционал, как то получилось ? В плане отключения картинок и замены фона. как например на сайте Миньюста . выплывающее меню сверху. С друпал не настолько знаком. Возможно какие то модули появились. 
Спасибо ! Если подскажете, как сделать соответствие , хотя бы примерное введенным требованиям для образовательных учреждений.

**Comment by alexd73** [comment]
Это начальная тема и в ней очень мало реализовано.
Мы планируем сделать такие же настройки, как и на большинстве государственных сайтов, а так же встроить озвучивание текста. Не хочется загадывать, но скорее всего скоро это сделаем ))

**Comment by alexd73** [comment]
Привет @krivtsov!
Посмотрите версию https://github.com/alexd73/accessibility_drupal_theme/tree/v7.x-1.x-dev
Добавили много интересного.
